language: node_js

node_js:
  - "9"

before_install:
  - export TZ='Asia/Shanghai'

script: 
  - npm run docs:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 
    secure: pYzmovVPiL8zZmHN9zwBLQ
  local_dir: docs/.vuepress/dist
  on:
    branch: master