language: node_js
node_js:
- '9'
before_install:
- export TZ='Asia/Shanghai'
script:
- npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github-token:
    secure: XrzHg/sscVO9xSAXQgKrILbiEo+iNqq/OFiQe0kQkyuXHXlphzWruJbuK2JImf4/oGPM2OJXgylXZ2H20iHcT9t3lhYChLzeb+yfapFN8thGJl7S27mNUUlj5lMbdCWWWIDxx3d/gSsQUeUgJCMQWk/tdjDtKsGc5D0xlAg2t1kbmt8qPkInkoSnuygLhOLfItSJ8unlMnEXAjtaaEDQl4lS0KQwsvaLO5h1bAnvAM/pCXQBV4vpJqCnALtoqDJ9bl9GPqhygjl3lJ2dOvruJXRJGCCz1/D/x924s+HbAMlAKhaHAcsucFH0TFwkk6nHxY1ncVd0zAs1h2E48X1wFEjjYVbPQ1LD2x6cIT9UuYuqUeP9UjBmyGai0tiWPxBf9OJSOZ37W2AcVJLBHgFD7cp59uQN7RTlNw1QPFOnjjdXMr8bVTT7eIf/LWcWDFLJ2gmox+0ZYUcgaF48mMN3WEPc0wyp0LcvQmJzxXnPcxdd69QHLSeiToGBSdIh+ZzAM4Fi21hl1bgLXdzxpWdJ7Seh9sHIFmpuIPAzsWYYEc6l6np6PJEtdSP2IWPM7WAWlf6gBhNwuJ2YFcKt9VBz02vqJ0v8+tR3Zp9ROV1bUtmz5PBrUyYu3VQ/PNPme49jHD/2ZqTQg+R6xpDAQLxP04EZowSmSF9tIlrI0mgdk8Q=
  on:
    branch: master
